url: http://haroon.amanullah.org

plugins:
  - jekyll-feed

feed:
  collections:
    journal:
      path: "/journal-feed.xml"

exclude:
  - .vscode/
  - .github/
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  nodes:
    output: true
    permalink: /nodes/:path
  projects:
    output: true
    permalink: /projects/:path
  journal:
    output: true
    permalink: /journal/:path
  writings:
    output: true
    permalink: /writing/:path
  guides:
    output: true
    permalink: /guide/:path