exclude:
  - .vscode/
  - .github/
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  nodes:
    output: true
    permalink: /nodes/:path
  projects:
    output: true
    permalink: /projects/:path
